version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres-image'
    build:
      context: .
    container_name: container_homework_docker_compose
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=052003
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/expense_tracking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=052003
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8082:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=052003
      - POSTGRES_DB=expense_tracking
    ports:
      - "5434:5432"
    volumes:
      - volume_docker_compose:/var/lib/postgresql/data

volumes:
  volume_docker_compose:
